# Site settings
title: Shauryaa.in
description: A website about me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shauryaa.in" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shauryaa
user_description: "I'm just a kid"
user_title: 
email: mail@shauryaa.in
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
# disqus_username: lorem_ipsum
instagram_username: arounddeeworld

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
